In [5]:
# We import pandas into Python
import pandas as pd

# We read in a stock data data file into a data frame and see what it looks like
vgg_structure = pd.read_csv('./vgg_structure.csv')

# We display the first 5 rows of the DataFrame
vgg_structure.head()

   layer  type     Xi     Yi      C      M    R    S     Xo     Yo
0  conv1   1.0  224.0  224.0    3.0   64.0  3.0  3.0  224.0  224.0
1  conv2   1.0  224.0  224.0   64.0   64.0  3.0  3.0  224.0  224.0
2  conv3   1.0  112.0  112.0   64.0  128.0  3.0  3.0  112.0  112.0
3  conv4   1.0  112.0  112.0  128.0  128.0  3.0  3.0  112.0  112.0
4  conv5   1.0   56.0   56.0  128.0  256.0  3.0  3.0   56.0   56.0